# Generated by Django 4.2.1 on 2023-08-01 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nit", models.IntegerField()),
                ("razon_social", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=15)),
                ("contacto", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("direccion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="EstadoServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="LugaresATratar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Medida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("categoria_toxicologica", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_ejecucion", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.cliente",
                    ),
                ),
                (
                    "estado_servicio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="servicios.estadoservicio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoControlImplementado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TipoServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ServicioLavadoTanque",
            fields=[
                (
                    "servicio_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="servicios.servicio",
                    ),
                ),
                (
                    "ubicacion_tanque",
                    models.CharField(
                        choices=[
                            ("opcion1", "Opción 1"),
                            ("opcion2", "Opción 2"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("otro_ubicacion_tanque", models.CharField(blank=True, max_length=100)),
                (
                    "material_tanque",
                    models.CharField(
                        choices=[
                            ("opcion1", "Opción 1"),
                            ("opcion2", "Opción 2"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("otro_material_tanque", models.CharField(blank=True, max_length=100)),
                ("revestimiento_tanque", models.CharField(max_length=100)),
                ("volumen_almacenamiento", models.FloatField()),
                (
                    "unidad_medida",
                    models.CharField(
                        choices=[("mt3", "m³"), ("lt", "L")], max_length=3
                    ),
                ),
                (
                    "estado_interno_tanque",
                    models.CharField(
                        choices=[("opcion1", "Opción 1"), ("opcion2", "Opción 2")],
                        max_length=20,
                    ),
                ),
                (
                    "fotos_estado_interno",
                    models.ImageField(upload_to="fotos_estado_interno"),
                ),
                (
                    "hermeticidad_tanque",
                    models.CharField(
                        choices=[("opcion1", "Opción 1"), ("opcion2", "Opción 2")],
                        max_length=20,
                    ),
                ),
                (
                    "fotos_hermeticidad",
                    models.ImageField(upload_to="fotos_hermeticidad"),
                ),
                (
                    "estado_empaques",
                    models.CharField(
                        choices=[("opcion1", "Opción 1"), ("opcion2", "Opción 2")],
                        max_length=20,
                    ),
                ),
                (
                    "fotos_estado_empaques",
                    models.ImageField(upload_to="fotos_estado_empaques"),
                ),
                (
                    "estado_tuberias",
                    models.CharField(
                        choices=[("opcion1", "Opción 1"), ("opcion2", "Opción 2")],
                        max_length=20,
                    ),
                ),
                (
                    "fotos_estado_tuberias",
                    models.ImageField(upload_to="fotos_estado_tuberias"),
                ),
                (
                    "observaciones_antes",
                    models.ImageField(upload_to="observaciones_antes"),
                ),
                (
                    "observaciones_despues",
                    models.ImageField(upload_to="observaciones_despues"),
                ),
            ],
            bases=("servicios.servicio",),
        ),
        migrations.CreateModel(
            name="Tecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="servicio",
            name="tipo_servicio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="servicios.tiposervicio",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ProductoUtilizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.producto",
                    ),
                ),
                (
                    "unidad_medida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.unidadmedida",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenciaMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.evidencia",
                    ),
                ),
                (
                    "medida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.medida",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AsignacionServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.servicio",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.tecnico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServicioFumigacion",
            fields=[
                (
                    "servicio_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="servicios.servicio",
                    ),
                ),
                (
                    "evidencias",
                    models.ManyToManyField(
                        through="servicios.EvidenciaMedida", to="servicios.evidencia"
                    ),
                ),
                (
                    "lugares_tratados",
                    models.ManyToManyField(blank=True, to="servicios.lugaresatratar"),
                ),
                (
                    "productos_utilizados",
                    models.ManyToManyField(
                        related_name="servicios_fumigacion",
                        through="servicios.ProductoUtilizado",
                        to="servicios.producto",
                    ),
                ),
                (
                    "tipo_control_implementado",
                    models.ManyToManyField(
                        blank=True, to="servicios.tipocontrolimplementado"
                    ),
                ),
            ],
            bases=("servicios.servicio",),
        ),
        migrations.AddField(
            model_name="productoutilizado",
            name="servicio_fumigacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_utilizados_rel",
                to="servicios.serviciofumigacion",
            ),
        ),
        migrations.AddField(
            model_name="evidenciamedida",
            name="servicio_fumigacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidencias_medidas",
                to="servicios.serviciofumigacion",
            ),
        ),
    ]
