# Generated by Django 4.2.1 on 2023-11-08 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaToxicologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField()),
                ('razon_social', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('contacto', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEmpaques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoInternoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTuberias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HermeticidadTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media/anexoImagenes/')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LugaresATratar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Precauciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RevestimientoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.cliente')),
                ('estado_servicio', models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.estadoservicio')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioFumigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(max_length=500, null=True)),
                ('lugares_tratados', models.ManyToManyField(blank=True, to='servicios.lugaresatratar')),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_fumigacion', to='servicios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='TipoControlImplementado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionRev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedidaTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.recomendaciones')),
                ('servicio_fumigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.serviciofumigacion')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioPrecaucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precaucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.precauciones')),
                ('servicio_fumigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.serviciofumigacion')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioLavadoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_almacenamiento', models.FloatField()),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('otra_ubicacion_tanque', models.CharField(blank=True, max_length=50, null=True)),
                ('otro_material_tanque', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_empaque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.estadoempaques')),
                ('estado_interno_tanque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.estadointernotanque')),
                ('estado_tuberias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.estadotuberias')),
                ('hermeticidad_tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.hermeticidadtanque')),
                ('material_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.materialtanque')),
                ('revestimiento_tanque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.revestimientotanque')),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_lavado_tanque', to='servicios.servicio')),
                ('ubicacion_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.ubicaciontanque')),
                ('unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.unidadmedidatanque')),
            ],
        ),
        migrations.AddField(
            model_name='serviciofumigacion',
            name='tipo_control_implementado',
            field=models.ManyToManyField(blank=True, to='servicios.tipocontrolimplementado'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.tiposervicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_toxixologica', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='servicios.categoriatoxicologica')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.producto')),
                ('servicio_fumigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_utilizados', to='servicios.serviciofumigacion')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.evidencia')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.medida')),
                ('servicio_fumigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_medidas', to='servicios.serviciofumigacion')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.ubicacionrev')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoLavadoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagenes', models.ManyToManyField(to='servicios.imagen')),
                ('servicio_Lavado', models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='servicios.serviciolavadotanque')),
            ],
        ),
    ]
