# Generated by Django 4.2.1 on 2023-08-11 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenciaConMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.evidencia",
                    ),
                ),
                (
                    "medida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.medida",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="serviciofumigacion",
            name="evidencias_con_medida",
            field=models.ManyToManyField(to="servicios.evidenciaconmedida"),
        ),
    ]
