# Generated by Django 4.2.1 on 2023-08-01 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evidenciamedida",
            name="servicio_fumigacion",
        ),
        migrations.RemoveField(
            model_name="productoutilizado",
            name="servicio_fumigacion",
        ),
        migrations.RemoveField(
            model_name="serviciofumigacion",
            name="evidencias",
        ),
        migrations.RemoveField(
            model_name="serviciofumigacion",
            name="productos_utilizados",
        ),
        migrations.AddField(
            model_name="serviciofumigacion",
            name="evidencia_medida",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subformulariosevidencia",
                to="servicios.evidenciamedida",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serviciofumigacion",
            name="producto_utilizado",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subformulariosprod",
                to="servicios.productoutilizado",
            ),
            preserve_default=False,
        ),
    ]
