# Generated by Django 4.2.1 on 2023-11-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_anexoimagen_delete_anexolavadotanque_delete_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='infoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=150)),
                ('no_radicado', models.CharField(max_length=150)),
                ('fecha_radicado', models.CharField(max_length=510)),
                ('TRD_radicado', models.CharField(max_length=150)),
                ('concepto_radicado', models.CharField(max_length=200)),
                ('agradecimiento', models.CharField(max_length=200)),
                ('compromiso', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=150)),
                ('pagina_web', models.CharField(max_length=150)),
                ('procedimiento_basico', models.CharField(max_length=500)),
            ],
        ),
    ]
