# Generated by Django 4.2 on 2023-04-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_rename_cliente_servicio_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='clientes',
        ),
        migrations.AddField(
            model_name='servicio',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.cliente'),
        ),
    ]
