# Generated by Django 4.2.1 on 2023-08-02 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0002_remove_evidenciamedida_servicio_fumigacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviciofumigacion",
            name="evidencia_medida",
        ),
        migrations.RemoveField(
            model_name="serviciofumigacion",
            name="producto_utilizado",
        ),
        migrations.AddField(
            model_name="evidenciamedida",
            name="servicio_fumigacion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidencias_medidas",
                to="servicios.serviciofumigacion",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productoutilizado",
            name="servicio_fumigacion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_utilizados",
                to="servicios.serviciofumigacion",
            ),
            preserve_default=False,
        ),
    ]
