# Generated by Django 4.2.1 on 2023-11-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_infoempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoempresa',
            name='procedimiento_basico',
            field=models.CharField(max_length=1000),
        ),
    ]
