# Generated by Django 4.2.1 on 2023-10-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_estadointernotanque_materialtanque_ubicacionrev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciamedida',
            name='ubicacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='servicios.ubicacionrev'),
        ),
    ]
