# Generated by Django 4.2.1 on 2023-11-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_infoempresa_procedimiento_basico'),
    ]

    operations = [
        migrations.CreateModel(
            name='firmas_servicio_Lavado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media/firmas_lavado/')),
                ('descripcion', models.TextField()),
                ('servicio_Lavado', models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='servicios.serviciolavadotanque')),
            ],
        ),
        migrations.CreateModel(
            name='firmas_servicio_fumigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media/firmas_fumigacion/')),
                ('servicio_fumigacion', models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='servicios.serviciofumigacion')),
            ],
        ),
    ]
