# Generated by Django 4.2.1 on 2023-10-18 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_evidenciamedida_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaToxicologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria_toxicologica',
        ),
        migrations.AlterField(
            model_name='productoutilizado',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.categoriatoxicologica'),
        ),
    ]
