# Generated by Django 4.2.1 on 2023-11-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_firmas_servicio_lavado_firmas_servicio_fumigacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmas_servicio_lavado',
            name='descripcion',
        ),
    ]
