# Generated by Django 4.2.1 on 2023-10-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_categoriatoxicologica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoutilizado',
            name='categoria_toxixologica',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='servicios.categoriatoxicologica'),
        ),
        migrations.AlterField(
            model_name='productoutilizado',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.unidadmedida'),
        ),
    ]
