# Generated by Django 4.2.1 on 2023-11-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_remove_firmas_servicio_lavado_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmas_servicio_fumigacion',
            name='servicio_fumigacion',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='servicios.serviciofumigacion', unique=True),
        ),
        migrations.AlterField(
            model_name='firmas_servicio_lavado',
            name='servicio_Lavado',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='servicios.serviciolavadotanque', unique=True),
        ),
    ]
