# Generated by Django 4.2.1 on 2023-11-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_alter_firmas_servicio_fumigacion_servicio_fumigacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='estado_empaque',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='estado_interno_tanque',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='estado_tuberias',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='hermeticidad_tanque',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='material_tanque',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='otra_ubicacion_tanque',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='otro_material_tanque',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='revestimiento_tanque',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='ubicacion_tanque',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='volumen_almacenamiento',
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_almacenamiento', models.FloatField()),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('otra_ubicacion_tanque', models.CharField(blank=True, max_length=50, null=True)),
                ('otro_material_tanque', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_empaque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.estadoempaques')),
                ('estado_interno_tanque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.estadointernotanque')),
                ('estado_tuberias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.estadotuberias')),
                ('hermeticidad_tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.hermeticidadtanque')),
                ('material_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.materialtanque')),
                ('revestimiento_tanque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.revestimientotanque')),
                ('servicio_lavado_tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.serviciolavadotanque')),
                ('ubicacion_tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.ubicaciontanque')),
                ('unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.unidadmedidatanque')),
            ],
        ),
    ]
