# Generated by Django 4.2.1 on 2023-11-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_remove_serviciolavadotanque_estado_empaque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tanque',
            old_name='servicio_lavado_tanque',
            new_name='servicio_lavado',
        ),
    ]
