# Generated by Django 4.2.1 on 2023-10-29 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_alter_cliente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precauciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.recomendaciones')),
                ('servicio_fumigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.serviciofumigacion')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioPrecaucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precaucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.precauciones')),
                ('servicio_fumigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.serviciofumigacion')),
            ],
        ),
    ]
