# Generated by Django 4.2.1 on 2023-10-26 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_alter_cliente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precauciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='serviciofumigacion',
            name='precauciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.precauciones'),
        ),
        migrations.AddField(
            model_name='serviciofumigacion',
            name='recomendaciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.recomendaciones'),
        ),
    ]
