# Generated by Django 4.2.1 on 2023-11-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_rename_servicio_lavado_tanque_tanque_servicio_lavado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anexoimagen',
            old_name='servicio_Lavado',
            new_name='servicio_lavado',
        ),
    ]
