# Generated by Django 4.2.1 on 2023-10-30 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_precauciones_recomendaciones_serviciorecomendacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciofumigacion',
            name='observaciones',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado_servicio',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.estadoservicio'),
        ),
    ]
