# Generated by Django 4.2.1 on 2023-11-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_serviciofumigacion_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEmpaques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTuberias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HermeticidadTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='anexoImagenes/')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RevestimientoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='estado_empaques',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='fotos_estado_empaques',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='fotos_estado_interno',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='fotos_estado_tuberias',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='fotos_hermeticidad',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='observaciones_antes',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='observaciones_despues',
        ),
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='otro_ubicacion_tanque',
        ),
        migrations.AddField(
            model_name='serviciolavadotanque',
            name='observaciones',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serviciolavadotanque',
            name='otra_ubicacion_tanque',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviciolavadotanque',
            name='estado_interno_tanque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.estadointernotanque'),
        ),
        migrations.AlterField(
            model_name='serviciolavadotanque',
            name='material_tanque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.materialtanque'),
        ),
        migrations.AlterField(
            model_name='serviciolavadotanque',
            name='otro_material_tanque',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviciolavadotanque',
            name='ubicacion_tanque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.ubicaciontanque'),
        ),
        migrations.AlterField(
            model_name='serviciolavadotanque',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.unidadmedidatanque'),
        ),
        migrations.CreateModel(
            name='AnexoLavadoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagenes', models.ManyToManyField(to='servicios.imagen')),
            ],
        ),
        migrations.AddField(
            model_name='serviciolavadotanque',
            name='estado_empaque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.estadoempaques'),
        ),
        migrations.AlterField(
            model_name='serviciolavadotanque',
            name='estado_tuberias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.estadotuberias'),
        ),
        migrations.AlterField(
            model_name='serviciolavadotanque',
            name='hermeticidad_tanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.hermeticidadtanque'),
        ),
        migrations.AlterField(
            model_name='serviciolavadotanque',
            name='revestimiento_tanque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.revestimientotanque'),
        ),
    ]
