# Generated by Django 4.2.1 on 2023-11-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_rename_servicio_lavado_anexoimagen_servicio_lavado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('no_activo', 'No Activo')], default='activo', max_length=10),
        ),
    ]
