# Generated by Django 4.2.1 on 2024-01-02 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0011_cliente_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexoimagen',
            options={'verbose_name_plural': 'Anexos por Servicio Lavado'},
        ),
        migrations.AlterModelOptions(
            name='asignacionservicio',
            options={'verbose_name_plural': 'Servicios Asignados'},
        ),
        migrations.AlterModelOptions(
            name='categoriatoxicologica',
            options={'verbose_name_plural': 'Listado de Categorias Toxicologicas'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Lista de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='estadoempaques',
            options={'verbose_name_plural': 'Listado de Estado de los Empaques'},
        ),
        migrations.AlterModelOptions(
            name='estadointernotanque',
            options={'verbose_name_plural': 'Listado del Estado Interno del Tanque'},
        ),
        migrations.AlterModelOptions(
            name='estadoservicio',
            options={'verbose_name_plural': 'Estado de los Servicios'},
        ),
        migrations.AlterModelOptions(
            name='estadotuberias',
            options={'verbose_name_plural': 'Listado de Estados de las Tuberias'},
        ),
        migrations.AlterModelOptions(
            name='evidencia',
            options={'verbose_name_plural': 'Evidencias del Servicio'},
        ),
        migrations.AlterModelOptions(
            name='evidenciamedida',
            options={'verbose_name_plural': 'Evidencia'},
        ),
        migrations.AlterModelOptions(
            name='firmas_servicio_fumigacion',
            options={'verbose_name_plural': 'Firmas de Servicio Fumigacion'},
        ),
        migrations.AlterModelOptions(
            name='firmas_servicio_lavado',
            options={'verbose_name_plural': 'Firmas de Servicio Lavado'},
        ),
        migrations.AlterModelOptions(
            name='hermeticidadtanque',
            options={'verbose_name_plural': 'Listado de la Hermeticidad del Tanque'},
        ),
        migrations.AlterModelOptions(
            name='infoempresa',
            options={'verbose_name_plural': 'Informacion de la Empresa'},
        ),
        migrations.AlterModelOptions(
            name='lugaresatratar',
            options={'verbose_name_plural': 'Lista de Lugares Tratados por Servicio'},
        ),
        migrations.AlterModelOptions(
            name='materialtanque',
            options={'verbose_name_plural': 'Listado de Materiales del Tanque'},
        ),
        migrations.AlterModelOptions(
            name='medida',
            options={'verbose_name_plural': 'Tipos de Medida'},
        ),
        migrations.AlterModelOptions(
            name='precauciones',
            options={'verbose_name_plural': 'Listado de Precauciones'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Tipos de Producto'},
        ),
        migrations.AlterModelOptions(
            name='productoutilizado',
            options={'verbose_name_plural': 'Productos Utilizados por Servicio'},
        ),
        migrations.AlterModelOptions(
            name='recomendaciones',
            options={'verbose_name_plural': 'Listado de Recomendaciones'},
        ),
        migrations.AlterModelOptions(
            name='revestimientotanque',
            options={'verbose_name_plural': 'Listado del Revestimiento del Tanque'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name_plural': 'Lista de Servicios'},
        ),
        migrations.AlterModelOptions(
            name='serviciofumigacion',
            options={'verbose_name_plural': 'Listado de Servicio Fumigacion'},
        ),
        migrations.AlterModelOptions(
            name='serviciolavadotanque',
            options={'verbose_name_plural': 'Servicios de Lavado de Tanque'},
        ),
        migrations.AlterModelOptions(
            name='servicioprecaucion',
            options={'verbose_name_plural': 'Precauciones por Servicio'},
        ),
        migrations.AlterModelOptions(
            name='serviciorecomendacion',
            options={'verbose_name_plural': 'Recomenaciondes por Servicio'},
        ),
        migrations.AlterModelOptions(
            name='tanque',
            options={'verbose_name_plural': 'Tanque'},
        ),
        migrations.AlterModelOptions(
            name='tecnico',
            options={'verbose_name_plural': 'Listado de Tecnicos'},
        ),
        migrations.AlterModelOptions(
            name='tipocontrolimplementado',
            options={'verbose_name_plural': 'Tipo de Control Implementado'},
        ),
        migrations.AlterModelOptions(
            name='tiposervicio',
            options={'verbose_name_plural': 'Tipo de Servicios'},
        ),
        migrations.AlterModelOptions(
            name='ubicacionrev',
            options={'verbose_name_plural': 'Ubicacion Rev'},
        ),
        migrations.AlterModelOptions(
            name='ubicaciontanque',
            options={'verbose_name_plural': 'Listado de Ubicaciones del Tanque'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedidatanque',
            options={'verbose_name_plural': 'Listado de las Medidas de Tanque'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='created_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asociados', to=settings.AUTH_USER_MODEL),
        ),
    ]
