# Generated by Django 4.2.1 on 2023-11-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_estadoempaques_estadotuberias_hermeticidadtanque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciolavadotanque',
            name='anexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.anexolavadotanque'),
        ),
    ]
