# Generated by Django 4.2.1 on 2023-11-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_serviciolavadotanque_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciolavadotanque',
            name='otra_ubicacion_tanque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviciolavadotanque',
            name='otro_material_tanque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
