# Generated by Django 4.2.1 on 2024-01-02 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0012_alter_anexoimagen_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asociados', to=settings.AUTH_USER_MODEL),
        ),
    ]
