# Generated by Django 4.2.1 on 2024-01-05 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_alter_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
