# Generated by Django 4.2.1 on 2023-11-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_alter_imagen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciolavadotanque',
            name='anexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.anexolavadotanque'),
        ),
    ]
