# Generated by Django 4.2.1 on 2023-11-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_alter_serviciolavadotanque_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciolavadotanque',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
