# Generated by Django 4.2.1 on 2023-11-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0016_alter_serviciolavadotanque_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciolavadotanque',
            name='anexo',
        ),
        migrations.AddField(
            model_name='anexolavadotanque',
            name='servicio_Lavado',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='servicios.serviciolavadotanque'),
        ),
    ]
