# Generated by Django 5.0.3 on 2024-05-08 20:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0018_remove_cliente_user_alter_servicio_fecha_inicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='UsuarioCliente',
        ),
    ]
